var XLATTables = {
    'es-MX': {
        'active': 'activo',
        'accept': 'aceptar',
        'account': 'cuenta',
        'add': 'agregar',
        'address': 'dirección',
        'address line 1': 'línea de dirección 1',
        'address line 2': 'línea de dirección 2',
        'address name': 'nombre de dirección',
        'addresses': 'direcciones',
        'add address': 'agregue la dirección',
        'add an address now': 'crear una nueva dirección',
        'all rights reserved': 'todos los derechos reservados',
        'an address must be saved to the shipping, billing or both address books.': 'se debe seleccionar Envío o Facturación',
        'an address with that name already exists. please specify another name': 'Una dirección con ese nombre ya existe. Elija otro nombre de dirección.',
        'awaiting approval': 'a la espera de aprobación',
        'awaiting response': 'a la espera de respuesta',
        'billing': 'facturación',
        'billtoaddress': 'facturar a la dirección',
        'bill to address': 'facturar a la dirección',
        'billtocity': 'facturar a la ciudad',
        'bill to city': 'facturar a la ciudad',
        'billtocompanyname': 'facturar al nombre de la empresa',
        'bill to company name': 'facturar al nombre de la empresa',
        'billtocountry': 'facturar al país',
        'bill to country': 'facturar al país',
        'billtodetail': 'facturar a',
        'bill to detail': 'facturar a',
        'billtofirstname': 'facturar al nombre',
        'bill to firstname': 'facturar al nombre',
        'billtoid': 'facturar al identificador',
        'bill to id': 'facturar al identificador',
        'billtoidentifier': 'facturar al identificador',
        'bill to identifier': 'facturar al identificador',
        'billtolastname': 'facturar al apellido',
        'bill to lastname': 'facturar al apellido',
        'billtophone': 'facturar al teléfono',
        'bill to phone': 'facturar al teléfono',
        'billtostate': 'facturar al estado',
        'bill to state': 'facturar al estado',
        'billtostreet1': 'facturar a la calle 1',
        'bill to street 1': 'facturar a la calle 1',
        'billtostreet2': 'facturar a la calle 2',
        'bill to street 2': 'facturar a la calle 2',
        'billtozip': 'facturar al código postal',
        'bill to zip': 'facturar al código postal',
        'body': 'cuerpo',
        'cancel': 'cancelar',
        'canceled': 'cancelado',
        'cart': 'carro',
        'category': 'categoría',
        'category list': 'lista de categorías',
        'categories': 'categorías',
        'city': 'ciudad',
        'citytaxrate': 'tarifa de impuesto para la ciudad',
        'city tax rate': 'tarifa de impuesto para la ciudad',
        'company': 'empresa',
        'company name': 'nombre de la empresa',
        'complete': 'finalizar',
        'completed': 'finalizado',
        'compose': 'redactar',
        'conditions': 'condiciones',
        'conditions of use': 'condiciones de Uso',
        'confirm password': 'confirmar contraseña',
        'contact us': 'contacto ',
        'copyright': 'derecho de autor',
        'country': 'país',
        'costcenter': 'centro de costos',
        'cost center': 'centro de costos',
        'countytaxrate': 'tarifa de impuesto para el condado',
        'county tax rate': 'tarifa de impuesto para el condado',
        'create account': 'crear una cuenta',
        'creditcard': 'tarjeta de crédito',
        'credit card': 'tarjeta de crédito',
        'customizedproductid': 'id. del producto personalizado',
        'customized product id': 'id. del producto personalizado',
        'date': 'fecha',
        'datecanceled': 'fecha de cancelación',
        'date canceled': 'fecha de cancelación',
        'datecreated':	'fecha de creación',
        'date created':	'fecha de creación',
        'datedeclined': 'fecha de rechazo',
        'date declined': 'fecha de rechazo',
        'datefulfilled': 'fecha de cumplimiento',
        'date fulfilled': 'fecha de cumplimiento',
        'dateneeded': 'fecha de recepción estipulada',
        'date needed': 'fecha de recepción estipulada',
        'dateshipped': 'fecha de envío',
        'date shipped': 'fecha de envío',
        'datesubmitted': 'fecha de presentación',
        'date submitted': 'fecha de presentación',
        'datecompleted': 'fecha de finalización',
        'date completed': 'fecha de finalización',
        'declined': 'rechazado',
        'delete': 'eliminar',
        'delete selected': 'eliminar elementos seleccionados',
        'description': 'descripción',
        'display columns': 'mostrar columnas',
        'edit address': 'modificar dirección',
        'email': 'correo electrónico',
        'end date': 'fecha de finalización',
        'extendedprice': 'precio ampliado',
        'extended price': 'precio ampliado',
        'externalid': 'id. externo',
        'external id': 'id. externo',
        'favorite': 'favorite',
        'favorites': 'favoritos',
        'favorite orders': 'pedidos favoritos',
        'first': 'primero',
        'first name': 'nombre',
        'from': 'desde',
        'fromuser': 'nombre de usuario',
        'from user': 'nombre de usuario',
        'for': 'por',
        'id': 'id.',
        'inbox': 'bandeja de entrada',
        'item': 'articulo',
        'items': 'articulos',
        'last': 'último',
        'last name': 'apellido',
        'last day':	'último día',
        'last logon': 'último inicio de sesión',
        'last month': 'último mes',
        'last n orders': 'últimos n pedidos',
        'last order': 'último pedido',
        'last ordered':	'último pedido',
        'last 3 months': 'últimos 3 meses',
        'last transaction date': 'última fecha de transacción',
        'last updated':	'última actualización',
        'last week': 'última semana',
        'last year': 'último año',
        'lead time': 'plazo de entrega',
        'lineitem': 'partidas',
        'line item': 'partidas',
        'line item report': 'informe de partidas',
        'logon': 'iniciar sesión',
        'logon as existing user': 'iniciar sesión como usuario',
        'log out': 'cerrar sesión',
        'message': 'mensaje',
        'messages': 'mensajes',
        'my account': 'mi cuenta',
        'name': 'nombre',
        'new': 'nuevo',
        'new address': 'nueva dirección',
        'new report': 'nuevo informe',
        'next': 'siguiente',
        'none': 'ninguno',
        'of': 'de',
        'ok': 'aceptar',
        'only display last': 'últimos n pedidos',
        'open': 'abierto',
        'order': 'pedido',
        'orders': 'pedidos',
        'order id': 'id. de pedido',
        'orderstatus': 'estado de pedido',
        'order status': 'estado de pedido',
        'ordertype': 'tipo de pedido',
        'order type': 'tipo de pedido',
        'password': 'contraseña',
        'passwords do not match!': '¡Las contraseñas no coinciden!',
        'paymentmethod': 'método de pago',
        'payment method': 'método de pago',
        'phone': 'teléfono',
        'please enter a valid email address': 'por favor introduzca una dirección de correo válida',
        'please wait while we fetch all categories': 'por favor espere mientras buscamos a todas las categorías',
        'please wait while we fetch all products': 'por favor espere mientras buscamos a todos los productos',
        'please wait while we save your changes': 'por favor espere mientras salvamos los cambios',
        'powered by': 'desarrollado por',
        'previous': 'anterior',
        'price request': 'solicitud de precios',
        'price requests': 'solicitudes de precios',
        'product': 'producto',
        'products': 'productos',
        'production': 'producción',
        'productexternalid': 'id. externo del producto',
        'product external id': 'id. externo del producto',
        'product id': 'id. del producto',
        'productname': 'nombre del producto',
        'product name': 'nombre del producto',
        'purchaseorder': 'orden de compra',
        'purchase order': 'orden de compra',
        'quantity': 'cantidad',
        'quantity available': 'cantidad disponible',
        'quantitymultiplier': 'multiplicador de cantidad',
        'quantity multiplier': 'multiplicador de cantidad',
        'quantityshipped': 'cantidad enviada',
        'quantity shipped': 'cantidad enviada',
        'repeat': 'repetir',
        'repeat order': 'repetir pedido',
        'replenishment': 'reposición',
        'replenishment order': 'pedido de reposición',
        'replenishment orders': 'pedidos de reposición',
        'reply': 'responder',
        'report': 'informe',
        'reports': 'informes',
        'report data': 'datos del informe',
        'save': 'guardar',
        'saved reports': 'informes guardados',
        'save as new': 'guardar como nuevo',
        'save to billing address book': 'guardar en libreta de direcciones de facturación',
        'save to shipping address book': 'guardar en libreta de direcciones de envío',
        'search': 'buscar',
        'search orders': 'Criterios de Búsqueda',
        'select all': 'seleccionar todas',
        'send': 'enviar',
        'sent': 'enviado',
        'shipper': 'expedidor',
        'shipper acct number': 'número de cuenta del expedidor',
        'shipperaccountnumber': 'número de cuenta del expedidor',
        'shipper account number': 'número de cuenta del expedidor',
        'shipping': 'envío',
        'shipping address': 'dirección de envío',
        'ship addresses': 'direcciónes de envío',
        'ship to': 'enviar a',
        'shiptoaddress': 'enviar a la dirección',
        'ship to address': 'enviar a la dirección',
        'shiptocity': 'enviar a la ciudad',
        'ship to city': 'enviar a la ciudad',
        'shiptocompanyname': 'enviar al nombre de la empresa',
        'ship to company name': 'enviar al nombre de la empresa',
        'shiptocountry': 'enviar al país',
        'ship to country': 'enviar al país',
        'shiptodetail': 'enviar a',
        'ship to detail': 'enviar a',
        'shiptofirstname': 'enviar al nombre',
        'ship to first name': 'enviar al nombre',
        'shiptoid': 'enviar al identificador',
        'ship to id': 'enviar al identificador',
        'shiptoidentifier': 'enviar al identificador',
        'ship to identifier': 'enviar al identificador',
        'shiptolastname': 'enviar al apellido',
        'ship to last name': 'enviar al apellido',
        'shiptomultiple': 'enviar a varias direcciones',
        'ship to multiple': 'enviar a varias direcciones',
        'shiptomultipleaddresses': 'enviar a varias direcciones',
        'ship to multiple addresses': 'enviar a varias direcciones',
        'shiptophone': 'enviar al teléfono',
        'ship to phone': 'enviar al teléfono',
        'shiptostate': 'enviar al estado',
        'ship to state': 'enviar al estado',
        'shiptostreet1': 'enviar a la calle 1',
        'ship to street 1': 'enviar a la calle 1',
        'shiptostreet2': 'enviar a la calle 2',
        'ship to street 2': 'enviar a la calle 2',
        'shiptozip': 'enviar al código postal',
        'ship to zip': 'enviar al código postal',
        'sort by': 'ordenar',
        'spendingaccount': 'cuenta de gastos',
        'spending account': 'cuenta de gastos',
        'standard': 'estándar',
        'standard order': 'pedido estándar',
        'standard orders': 'pedidos estándares',
        'start date': 'fecha de inicio',
        'state': 'estado',
        'statetaxrate': 'tarifa de impuesto para el estado',
        'state tax rate': 'tarifa de impuesto para el estado',
        'status': 'estado',
        'subject': 'asunto',
        'submitted': 'presentado',
        'submitted date': 'fecha de presentación',
        'subtotal by column': 'subtotal en',
        'swipe product left for more info': 'Producto Pase a la izquierda para obtener más información',
        'taxcountyname': 'nombre de impuestos del condado',
        'tax county name': 'nombre de impuestos del condado',
        'taxcounty': 'impuestos del condado',
        'tax county': 'impuestos del condado',
        'timespan': 'intervalo de tiempo',
        'to':'para',
        'totalquantity': 'cantidad total',
        'total quantity': 'cantidad total',
        'type': 'tipo',
        'unit of measure': 'unidad de medida',
        'unitprice': 'precio unitario',
        'unit price': 'precio unitario',
        'unsubmitted': 'no presentado',
        'user': 'usuario',
        'user information': 'información del usuario',
        'username': 'nombre de usuario',
        'view orders': 'ver pedidos',
        'view product': 'ver producto',
        'your search resulted in no records. please refine your search.': 'la búsqueda no arrojó resultados.',
        'you have no addresses yet!': '¡No tiene direcciones aún!',
        'you have no favorite orders yet!': '¡No se guardaron pedidos favoritos!',
        'you have no messages yet!': '¡No tiene mensajes!',
        'zip': 'código postal',

        'product name: a to z': 'Nombre del producto: A a la Z',
        'product name: z to a': 'Nombre del producto: Z a la A',
        'product id: a to z': 'Id. de producto: A a la Z',
        'product id: z to a': 'Id. de producto: Z a la A',
        'price: lowest to highest': 'Precio: De menor a mayor',
        'price: highest to lowest': 'Precio: De mayor a menor',

        'your password does not meet the requirements set for length or complexity. it must be changed to meet the minimum requirements before continuing.': 'Su contraseña no cumple los requisitos establecidos para la longitud o complejidad. Debe cambiarla para cumplir los requisitos mínimos a fin de poder continuar.',
        'there are three distinct password security levels. the rules are defined as:': 'Hay tres niveles de seguridad de la contraseña distintos. Las reglas se definen como:',
        'low: no restrictions on passwords.': 'Bajo: contraseñas sin restricciones.',
        'medium: a minimum of 6 characters required.': 'Medio: se requiere un mínimo de 6 caracteres.',
        'high:': 'Alto:',
        'minimum of 8 alphanumeric characters.': 'se requiere un mínimo de 8 caracteres alfanuméricos.',
        'two or more of the following kinds of characters': 'Dos o más de los siguientes tipos de caracteres:',
        'alphabetic (e.g., a-z, A-Z)': 'Alfabéticos (por ejemplo, a-z, A-Z).',
        'numeric (i.e. 0-9)': 'Numéricos (por ejemplo, 0-9).',
        'punctuation and other characters (e.g.,': 'Puntuación y otros caracteres (por ejemplo,',
        '** after 6 failed logon attempts, the user will be locked out for 30 minutes.': '** Después de 6 intentos fallidos de inicio de sesión, el usuario se bloqueará durante 30 minutos.',

        'in your': function(parameters) {
            if(parameters == 1) return 'in your_s';
            else return 'in your_p';
        },
        'in your_s': 'en su',
        'in your_p': 'en la'
    }

};
