var XLATTables = {
    'es-MX': {
        'active': 'activo',
        'accept': 'aceptar',
        'account': 'cuenta',
        'add': 'agregar',
        'address': 'dirección',
        'addresses': 'direcciones',
        'all rights reserved': 'todos los derechos reservados',
        'awaiting approval': 'a la espera de aprobación',
        'awaiting response': 'a la espera de respuesta',
        'canceled': 'cancelado',
        'cart': 'carro',
        'category': 'categoría',
        'category list': 'lista de categorías',
        'categories': 'categorías',
        'complete': 'finalizar',
        'completed': 'finalizado',
        'conditions of use': 'condiciones de Uso',
        'contact us': 'contacto ',
        'copyright': 'derecho de autor',
        'declined': 'rechazado',
        'end date': 'fecha de finalización',
        'favorite': 'favorite',
        'favorites': 'favoritos',
        'id': 'id.',
        'item': 'articulo',
        'items': 'articulos',
        'log out': 'cerrar sesión',
        'message': 'mensaje',
        'messages': 'mensajes',
        'new': 'nuevo',
        'of': 'de',
        'only display last': 'últimos n pedidos',
        'open': 'abierto',
        'order': 'pedido',
        'orders': 'pedidos',
        'order id': 'id. de pedido',
        'powered by': 'desarrollado por',
        'price request': 'solicitud de precios',
        'price requests': 'solicitudes de precios',
        'product': 'producto',
        'products': 'productos',
        'production': 'producción',
        'replenishment order': 'pedido de reposición',
        'replenishment orders': 'pedidos de reposición',
        'report': 'informe',
        'reports': 'informes',
        'search': 'buscar',
        'search orders': 'Criterios de Búsqueda',
        'shipping address': 'dirección de envío',
        'standard order': 'pedido estándar',
        'standard orders': 'pedidos estándares',
        'start date': 'fecha de inicio',
        'status': 'estado',
        'submitted': 'presentado',
        'submitted date': 'fecha de presentación',
        'type': 'tipo',
        'unsubmitted': 'no presentado',
        'user information': 'información del usuario',
        'your search resulted in no records. please refine your search.': 'la búsqueda no arrojó resultados.',
        'in your': function(parameters) {
            if(parameters == 1) return 'in your_s';
            else return 'in your_p';
        },
        'in your_s': 'en su',
        'in your_p': 'en la'
    }

};
